// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	resources "github.com/shipyard-run/shipyard/pkg/config/resources"
	shipyard "github.com/shipyard-run/shipyard/pkg/shipyard"
	mock "github.com/stretchr/testify/mock"

	types "github.com/shipyard-run/hclconfig/types"
)

// Engine is an autogenerated mock type for the Engine type
type Engine struct {
	mock.Mock
}

// Apply provides a mock function with given fields: _a0
func (_m *Engine) Apply(_a0 string) ([]types.Resource, error) {
	ret := _m.Called(_a0)

	var r0 []types.Resource
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]types.Resource, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) []types.Resource); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Resource)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ApplyWithVariables provides a mock function with given fields: path, variables, variablesFile
func (_m *Engine) ApplyWithVariables(path string, variables map[string]string, variablesFile string) ([]types.Resource, error) {
	ret := _m.Called(path, variables, variablesFile)

	var r0 []types.Resource
	var r1 error
	if rf, ok := ret.Get(0).(func(string, map[string]string, string) ([]types.Resource, error)); ok {
		return rf(path, variables, variablesFile)
	}
	if rf, ok := ret.Get(0).(func(string, map[string]string, string) []types.Resource); ok {
		r0 = rf(path, variables, variablesFile)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Resource)
		}
	}

	if rf, ok := ret.Get(1).(func(string, map[string]string, string) error); ok {
		r1 = rf(path, variables, variablesFile)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Blueprint provides a mock function with given fields:
func (_m *Engine) Blueprint() *resources.Blueprint {
	ret := _m.Called()

	var r0 *resources.Blueprint
	if rf, ok := ret.Get(0).(func() *resources.Blueprint); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*resources.Blueprint)
		}
	}

	return r0
}

// Destroy provides a mock function with given fields:
func (_m *Engine) Destroy() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetClients provides a mock function with given fields:
func (_m *Engine) GetClients() *shipyard.Clients {
	ret := _m.Called()

	var r0 *shipyard.Clients
	if rf, ok := ret.Get(0).(func() *shipyard.Clients); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*shipyard.Clients)
		}
	}

	return r0
}

// ParseConfig provides a mock function with given fields: _a0
func (_m *Engine) ParseConfig(_a0 string) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ParseConfigWithVariables provides a mock function with given fields: _a0, _a1, _a2
func (_m *Engine) ParseConfigWithVariables(_a0 string, _a1 map[string]string, _a2 string) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, map[string]string, string) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ResourceCount provides a mock function with given fields:
func (_m *Engine) ResourceCount() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// ResourceCountForType provides a mock function with given fields: _a0
func (_m *Engine) ResourceCountForType(_a0 string) int {
	ret := _m.Called(_a0)

	var r0 int
	if rf, ok := ret.Get(0).(func(string) int); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

type mockConstructorTestingTNewEngine interface {
	mock.TestingT
	Cleanup(func())
}

// NewEngine creates a new instance of Engine. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewEngine(t mockConstructorTestingTNewEngine) *Engine {
	mock := &Engine{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
