# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: shipyard
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
- 
  env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  - GPG_TTY=$(tty)
  
  binary: shipyard

  flags:
    - -tags={.Tag}
 
  goos:
    - linux
    - darwin
    - windows

  goarch:
    - amd64
    - arm
    - arm64
  goarm:
    - 6
    - 7

brews:
  -
    name: shipyard
    github:
      owner: shipyard-run
      name: homebrew-repo

    commit_author:
      name: shipyardbot
      email: mail@shipyard.run

    homepage: "https://shipyard.run/"

nfpms:
  -
    package_name: shipyard
    vendor: Shipyard Inc
    homepage: https://shipyard.run
    formats:
      - deb
      - rpm

snapcrafts:
  -
    name: shipyard

archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format_overrides:
  - goos: windows
    format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
dockers:
  - image_templates:
    - shipyardrun/shipyard:{{ .Tag }}
signs:
  - artifacts: checksum