docs "docs" {
  path  = "./docs"
  port  = 8080
	open_in_browser = true

  # By default the index is autogenerated from the documents in the 'path'
  # to override this behaviour set the following environment parameters.
  
  # index_title = "Test"
  # index_pages = ["index", "other"]
}
