package mocks

import (
	types "github.com/jumppad-labs/hclconfig/types"
	providers "github.com/jumppad-labs/jumppad/pkg/providers"
	"github.com/jumppad-labs/jumppad/pkg/providers/mocks"
	mock "github.com/stretchr/testify/mock"
)

// Providers is an autogenerated mock type for the Providers type
type Providers struct {
	mock.Mock
	Providers  []*mocks.MockProvider
	returnVals map[string]error
}

func NewProviders(returnVals map[string]error) *Providers {
	_m := &Providers{}
	_m.Providers = []*mocks.MockProvider{}
	_m.returnVals = returnVals

	return _m
}

// GetProvider provides a mock function with given fields: c
func (_m *Providers) GetProvider(c types.Resource) providers.Provider {
	m := mocks.New(c)

	val := _m.returnVals[c.Metadata().Name]
	m.On("Create").Return(val)
	m.On("Destroy").Return(val)
	m.On("Refresh").Return(val)
	m.On("Changed").Return(val)

	_m.Providers = append(_m.Providers, m)
	return m
}
