package mocks

import (
	types "github.com/jumppad-labs/hclconfig/types"
	"github.com/jumppad-labs/jumppad/pkg/config"
	mock "github.com/stretchr/testify/mock"
)

// Providers is an autogenerated mock type for the Providers type
type Providers struct {
	mock.Mock
	Providers  []*Provider
	returnVals map[string]error
}

func NewProviders(returnVals map[string]error) *Providers {
	_m := &Providers{}
	_m.Providers = []*Provider{}
	_m.returnVals = returnVals

	return _m
}

// GetProvider provides a mock function with given fields: c
func (_m *Providers) GetProvider(c types.Resource) config.Provider {
	m := &Provider{}

	val := _m.returnVals[c.Metadata().Name]
	m.On("Create").Return(val)
	m.On("Destroy").Return(val)
	m.On("Refresh").Return(val)
	m.On("Changed").Return(false, val)
	m.On("Init", mock.Anything, mock.Anything).Return(nil)

	m.Init(c, nil)
	_m.Providers = append(_m.Providers, m)
	return m
}
